on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "testing java file"
        run: echo "java file"
      - name: Compile Java files
        run: javac *.java
      - name: Run Java program
        run: java y
